### ISSUE TITLE
MySQL is missing from Selecting a Datastore

### ISSUE THREAD

**Issue by derekperkins** [authzed/docs#63] opened 2022-08-04 20:56 UTC
Not sure if there just aren't MySQL specific flags or if this is an oversight

https://github.com/authzed/docs/blob/main/docs/spicedb/selecting-a-datastore.md
https://docs.authzed.com/spicedb/selecting-a-datastore#mysql

**Comment by derekperkins** [comment] 2022-09-07 05:18
Thanks for adding that! Is there anything to know if I'm using Vitess as the backing store? I saw the note in the PR about adding more context in the future.

Fixed by #65

**Comment by jzelinskie** [comment] 2022-09-28 17:04
cc @vroldanbet who knows best

I believe the MySQL datastore with the intent of being used primarily with Vitess. It was contributed by GitHub who is one of the largest Vitess users.

**Comment by vroldanbet** [comment] 2022-09-30 15:28
The MySQL Datastore was designed with Vitess in mind, but nothing in SpiceDB's test suite prevents it from ending up being incompatible with Vitess as the code evolves, because the tests execute only against MySQL . The best course of action would be to create a new test suite that uses Vitess instead of a vanilla MySQL. 

I cannot guarantee incompatible changes haven't been introduced ever since, but I'd be surprised since it hasn't changed that much after getting open sourced.

**Comment by josephschorr** [comment] 2022-11-17 17:44
Closing; please reopen a new issue about Vitess if interested @derekperkins

**Closed by josephschorr** 2022-11-17 17:44 UTC
